### ISSUE TITLE
Not 3 formes!!!

### ISSUE THREAD

**Issue by LFL38** [Fusion-thermo/Block-Blast#1]
C:\Users\Floppa\Desktop\BlockBlast>python github\blokcs.py      
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=247, reference=35
Color channel 1: measured=236, reference=45
Color channel 2: measured=225, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=36, reference=35
Color channel 1: measured=32, reference=45
Color channel 2: measured=56, reference=85
Color channel 0: measured=0, reference=35
Color channel 1: measured=0, reference=45
Color channel 2: measured=0, reference=85
Scanning for pieces...
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (0, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (1, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (2, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (3, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (4, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (5, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (6, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (7, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (8, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (9, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (10, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (11, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (12, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (13, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (14, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Found piece pixel at (15, 1)
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139
Color channel 0: measured=0, reference=48
Color channel 1: measured=0, reference=74
Color channel 2: measured=0, reference=139

Detected grid:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Traceback (most recent call last):
  File "C:\Users\Floppa\Desktop\BlockBlast\github\blokcs.py", line 311, in <module>
    raise Exception("Not 3 shapes")
Exception: Not 3 shapes

**Comment by Fusion-thermo** [comment]
Code and readme updated

This error could be due to updates of the app and I do not plan to update the code to match.

**Comment by Fusion-thermo** [comment]
Code and readme updated

This error could be due to updates of the app and I do not plan to update the code to match.
